datasets:
  ec_instruct:
    data_type: 1d_protein
    build_info:
      storage1: /mnt/default/users/v-changma1/ProteinBlip/dataset/protein_instruction_tuning_v2/ec-train-instruction-pdb.txt
      storage2: /mnt/default/users/v-changma1/ProteinBlip/dataset/protein_instruction_tuning_v2/ec-train-instruction-swissprot.txt